import { AlertTriangle, Send, X } from 'lucide-react';

const CompetitionSubmitModal = ({ open, total, saved, errors, pending, loading, error, onCancel, onConfirm, theme }) => {
    if (!open) return null;
    const isDark = theme === 'dark';
    const surface = isDark ? 'bg-slate-900 text-slate-100 shadow-black/50' : 'bg-white text-blue-950 shadow-blue-950/25';
    const cancelButton = isDark ? 'border-slate-700 text-blue-200 hover:bg-slate-800' : 'border-blue-100 text-blue-800 hover:bg-blue-50';

    return <div className="fixed inset-0 z-50 grid place-items-center bg-slate-950/60 p-4"><section className={`w-full max-w-md rounded-2xl p-5 shadow-2xl sm:p-6 ${surface}`}><div className="flex items-start justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-wide text-blue-700 dark:text-blue-300">Xác nhận</p><h2 className="mt-1 text-xl font-bold">Nộp bài ngay?</h2></div><button type="button" onClick={onCancel} className={`inline-flex h-9 w-9 cursor-pointer items-center justify-center rounded-lg ${isDark ? 'text-slate-300 hover:bg-slate-800' : 'text-gray-500 hover:bg-blue-50'}`} aria-label="Đóng"><X size={19} /></button></div><div className="mt-5 grid grid-cols-3 gap-2"><div className="rounded-xl bg-green-100 p-3 text-center text-green-700 dark:bg-green-500/15 dark:text-green-300"><p className="text-lg font-bold">{saved}</p><p className="text-xs font-semibold">Đã lưu</p></div><div className="rounded-xl bg-yellow-100 p-3 text-center text-yellow-800 dark:bg-yellow-500/15 dark:text-yellow-300"><p className="text-lg font-bold">{pending}</p><p className="text-xs font-semibold">Đang lưu</p></div><div className="rounded-xl bg-red-100 p-3 text-center text-red-700 dark:bg-red-500/15 dark:text-red-300"><p className="text-lg font-bold">{errors}</p><p className="text-xs font-semibold">Lỗi lưu</p></div></div><p className={`mt-4 text-sm leading-6 ${isDark ? 'text-slate-300' : 'text-gray-600'}`}>Tổng {total} câu. Hệ thống sẽ chờ tất cả đáp án được xác nhận trước khi nộp bài.</p>{error ? <p className="mt-3 flex items-start gap-2 rounded-xl bg-red-50 p-3 text-sm font-semibold text-red-700 dark:bg-red-950/45 dark:text-red-300"><AlertTriangle size={17} className="mt-0.5 shrink-0" />{error}</p> : null}<div className="mt-5 flex gap-3"><button type="button" onClick={onCancel} disabled={loading} className={`h-11 flex-1 cursor-pointer rounded-xl border text-sm font-bold disabled:cursor-not-allowed disabled:opacity-50 ${cancelButton}`}>Tiếp tục làm</button><button type="button" onClick={onConfirm} disabled={loading || errors > 0} className="inline-flex h-11 flex-1 cursor-pointer items-center justify-center gap-2 rounded-xl bg-blue-800 text-sm font-bold text-white hover:bg-blue-900 disabled:cursor-not-allowed disabled:opacity-50"><Send size={16} />{loading ? 'Đang nộp...' : 'Nộp bài'}</button></div></section></div>;
};

export default CompetitionSubmitModal;
